[phases.setup]
nixPkgs = []
nixOverlays = []
aptPkgs = ["curl", "ca-certificates", "gnupg", "wget"]

[phases.caddy]
dependsOn = ["setup"]
nixPkgs = ["caddy"]
nixpkgsArchive = "ba913eda2df8eb72147259189d55932012df6301"
nixOverlays = []
cmds = ["caddy fmt --overwrite /assets/Caddyfile"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "curl -fsSL https://deb.nodesource.com/setup_22.x | bash -",
  "apt-get install -y nodejs",
  "npm ci"
]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = ["node_modules/.cache"]

[start]
cmd = "exec caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"
